import { defineConfig } from 'vite'
import { resolve } from 'path'
import handlebars from 'vite-plugin-handlebars'
import tailwindcss from '@tailwindcss/vite'

// Общие данные, доступные во всех шаблонах
const siteData = {
  siteName: 'Abiroy',
  year: new Date().getFullYear(),
  nav: [
    { href: '/index.html', label: 'Главная' },
    { href: '/solution.html', label: 'Решения' },
    { href: '/technologies.html', label: 'Технологии' },
    { href: '/products.html', label: 'Продукция' },
    { href: '/services.html', label: 'Услуги' },
    { href: '/cases.html', label: 'Кейсы и Клиенты' },
    { href: '/about.html', label: 'О компании' },
    { href: '/contact.html', label: 'Контакты' },
  ],
  products: [
    {
      img: '/product-1.png',
      code: 'U1013CABDVCR',
      name: 'Обратный осмос RO-750.',
      flow: '1.2 m³/h',
      people: 'Для 3 чел.',
      price: '9 990 KZT',
      popular: true,
    },
    {
      img: '/product-2.png',
      code: 'U1013CABDVCR',
      name: 'ABIROY RO –250/RO–1000',
      flow: '1.2 m³/h',
      people: 'Для 3 чел.',
      price: '9 990 KZT',
      popular: true,
    },
    {
      img: '/product-3.png',
      code: 'U1013CABDVCR',
      name: 'ABIROY RO –1/RO-10',
      flow: '1.2 m³/h',
      people: 'Для 3 чел.',
      price: '9 990 KZT',
      popular: true,
    },
    {
      img: '/product-4.png',
      code: 'U1013CABDVCR',
      name: 'Wasser Line',
      flow: '1.2 m³/h',
      people: 'Для 3 чел.',
      price: '9 990 KZT',
      popular: true,
    },
    {
      img: '/product-ro.png',
      code: 'U1013CABDVCR',
      name: 'Мембраны обратного осмоса',
      flow: '1.2 m³/h',
      people: 'Для 3 чел.',
      price: '9 990 KZT',
      popular: true,
    },
    {
      img: '/product-6.png',
      code: 'U1013CABDVCR',
      name: 'Корпуса мембран обратного осмоса',
      flow: '1.2 m³/h',
      people: 'Для 3 чел.',
      price: '9 990 KZT',
      popular: true,
    },
  ],
  services: [
    {
      img: '/service-1.png',
      desc: 'Система очистки воды, установленная в транспортном контейнере, недорога в транспортировке и проста в применении. Кроме того, модульность позволяет комбинировать разные технологические решения, так же используя данную методику возможно сформировать системы большой производительности.',
      title: 'Станций водоподготовки блок-модульного типа.',
      brand: 'ECOSOFT',
    },
    {
      img: '/service-2.png',
      desc: 'Мы возьмём на себя все заботы — приедем на Ваш объект, заполним техническое задание, отберем пробу воды, сделаем подробный химический анализ в лаборатории, подберем самое качественное и надежное оборудование для очистки воды в частном доме, учтем все Ваши требования и пожелания, смонтируем и возьмём на обслуживание систему водоподготовки.',
      title: 'Профессиональный подбор и монтаж оборудования очистки воды.',
      brand: 'ECOSOFT',
    },
    {
      img: '/service-3.png',
      desc: 'Обратный осмос — самый стабильный энергоэффективный метод обессоливания воды в промышленной водоподготовке. Применение промышленных установок обратного осмоса – очистка воды (деионизация воды) для технологических целей предприятия и производство питьевой воды во многих отраслях промышленности.',
      title: 'Производство промышленных систем обратного осмоса производительностью от 0,25м3/час до 30 м3/час.',
      brand: 'ECOSOFT',
    },
    {
      img: '/product-ro.png',
      desc: 'Компания Aburoy Group предоставляет услуги по замене картриджей, ремонту и установки фильтров для воды. Выезд и диагностика в черте города Нур Султан бесплатно.',
      title: 'Ремонт, замена, установка фильтров для воды.',
      brand: 'ECOSOFT',
    },
  ],
  certificates: ['/cert-1.png', '/cert-2.png', '/cert-3.png', '/cert-4.png'],
  techCatalog: [
    {
      metric: '0,01–0,1 мкм',
      metricSub: 'размер пор мембраны',
      tag: 'мембранная очистка',
      title: 'Ультрафильтрация',
      img: '/hero.png',
    },
    {
      metric: 'До 99%',
      metricSub: 'удаление растворенных солей',
      tag: 'деминерализованная',
      title: 'Системы обратного осмоса',
      img: '/hero.png',
    },
    {
      metric: 'От 1 контейнера',
      metricSub: 'готовая станция водоподготовки',
      tag: 'модульное решение',
      title: 'Контейнерные станции',
      img: '/hero.png',
    },
    {
      metric: 'До 18 МОм·см',
      metricSub: 'удельное сопротивление воды',
      tag: 'очистка после RO',
      title: 'Электродеионизация',
      img: '/hero.png',
    },
  ],
  aboutText:
    'Непрерывно повышающиеся требования, предъявляемые в последнее время к качеству пищевой продукции (особенно в той части, где основным компонентом является вода)',
  faqText:
    'Непрерывно повышающиеся требования, предъявляемые в последнее время к качеству пищевой продукции (особенно в той части, где основным компонентом является вода)',
  faq: [
    {
      q: 'Вопрос',
      a: 'Непрерывно повышающиеся требования, предъявляемые в последнее время к качеству пищевой продукции (особенно в той части, где основным компонентом является вода)',
    },
    {
      q: 'Системы Обратного Осмоса',
      a: 'Непрерывно повышающиеся требования, предъявляемые в последнее время к качеству пищевой продукции (особенно в той части, где основным компонентом является вода)',
      open: true,
    },
    {
      q: 'Вопрос',
      a: 'Непрерывно повышающиеся требования, предъявляемые в последнее время к качеству пищевой продукции (особенно в той части, где основным компонентом является вода)',
    },
    {
      q: 'Вопрос',
      a: 'Непрерывно повышающиеся требования, предъявляемые в последнее время к качеству пищевой продукции (особенно в той части, где основным компонентом является вода)',
    },
    {
      q: 'Вопрос',
      a: 'Непрерывно повышающиеся требования, предъявляемые в последнее время к качеству пищевой продукции (особенно в той части, где основным компонентом является вода)',
    },
  ],
  caseDesc:
    'Приоритетным направлением в развитии энергетической отрасли становится необходимость ввода новых и реконструкции существующих мощностей.',
  cases: [
    {
      img: '/hero.png',
      company: 'Название компании',
      title: 'Название кейса',
      industry: 'Энергетика',
      technology: 'Обратный осмос',
      solution: 'Промышленные системы',
    },
    {
      img: '/case-2.png',
      company: 'Название компании',
      title: 'Название кейса',
      industry: 'Промышленность',
      technology: 'Ультрафильтрация',
      solution: 'Контейнерные станции',
    },
    {
      img: '/hero.png',
      company: 'Название компании',
      title: 'Название кейса',
      industry: 'Строительство',
      technology: 'EDI',
      solution: 'Модульные системы',
    },
    {
      img: '/case-2.png',
      company: 'Название компании',
      title: 'Название кейса',
      industry: 'Энергетика',
      technology: 'Ультрафильтрация',
      solution: 'Контейнерные станции',
    },
    {
      img: '/hero.png',
      company: 'Название компании',
      title: 'Название кейса',
      industry: 'Промышленность',
      technology: 'Обратный осмос',
      solution: 'Промышленные системы',
    },
    {
      img: '/case-2.png',
      company: 'Название компании',
      title: 'Название кейса',
      industry: 'Строительство',
      technology: 'EDI',
      solution: 'Модульные системы',
    },
  ],
  productCatalog: [
    { title: 'Промышленные установки обратного осмоса', img: '/product-ro.png' },
    { title: 'Промышленные обратноосмотические мембраны и корпуса', img: '/product-ro.png' },
    { title: 'Фильтрующие материалы', img: '/product-ro.png' },
    { title: 'Корпуса колонных фильтров', img: '/product-ro.png' },
    { title: 'Комплектующие для фильтров колонного типа', img: '/product-ro.png' },
    { title: 'Клапана управления для фильтров колонного типа', img: '/product-ro.png' },
    { title: 'Насосы повышения давления', img: '/product-ro.png' },
    { title: 'Насос дозаторы для систем водоподготовки', img: '/product-ro.png' },
    { title: 'Комплектующие для систем обратного осмоса', img: '/product-ro.png' },
    { title: 'Локальные станции очистки воды', img: '/product-ro.png' },
    { title: 'Умягчители воды', img: '/product-ro.png' },
    { title: 'Обезжелезователи воды колонного типа', img: '/product-ro.png' },
  ],
  stepDesc: 'Приоритетным направлением в развитии энергетической отрасли становится',
  steps: [
    { n: '01', title: 'Запрос' },
    { n: '02', title: 'Анализ воды' },
    { n: '03', title: 'Тех. задание' },
    { n: '04', title: 'Коммерческое Предложение' },
    { n: '05', title: 'Поставка' },
    { n: '06', title: 'Монтаж/пир', spacerBefore: true },
    { n: '07', title: 'Сервис' },
  ],
}

export default defineConfig({
  plugins: [
    tailwindcss(),
    handlebars({
      partialDirectory: resolve(__dirname, 'src/partials'),
      context: siteData,
    }),
  ],
  build: {
    rollupOptions: {
      input: {
        index: resolve(__dirname, 'index.html'),
        about: resolve(__dirname, 'about.html'),
        contact: resolve(__dirname, 'contact.html'),
        technologies: resolve(__dirname, 'technologies.html'),
        'techo-detail': resolve(__dirname, 'techno-details.html'),
        cases: resolve(__dirname, 'cases.html'),
        'case-details': resolve(__dirname, 'case-details.html'),
        solution: resolve(__dirname, 'solution.html'),
        'solution-details': resolve(__dirname, 'solution-details.html'),
        products: resolve(__dirname, 'products.html'),
        services: resolve(__dirname, 'services.html'),
        'service-detail': resolve(__dirname, 'service-detail.html'),
        'goods-details': resolve(__dirname, 'goods-details.html'),
        goods: resolve(__dirname, 'goods.html'),
        privacy: resolve(__dirname, 'privacy.html'),
        404: resolve(__dirname, '404.html'),
      },
    },
  },
})
